#!/usr/bin/env bash

set -euo pipefail

cd "${0%/*}"/

[[ -z ${1:-} ]] && {
  echo "usage: ${0##*/} url [desc]"
  exit 1
}
# set vars
url=$1
desc=${2:-$url}

# if no desc given - attempt download title
[[ -z ${2:-} ]] && {
  shopt -s nocasematch
  title="<title>(.*)?</title>"
  while read -r line; do
    if [[ $line =~ $title ]]; then
      desc="$url » ${BASH_REMATCH[1]}"
    fi
  done < <(curl -sL "$url")
}

echo "- [$desc]($url)" >> "${0%/*}"/README.md
echo "written: [$desc]($url)"
read -r -p "commit? [N/y] " ans
if [[ "${ans:0:1}" =~ [Yy] ]]; then
  git add README.md
  git commit -m "Added $url"
  git push origin main
fi
